"""create_diagram_attributes

Revision ID: 4c29f039a654
Revises: 72adc2dd80b2
Create Date: 2026-09-13 00:15:13.938705

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c29f039a654'
down_revision: Union[str, Sequence[str], None] = '72adc2dd80b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_attributes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(NOT is_primary_key) OR (position = 0 AND data_type = 'UUID' AND NOT is_nullable)", name='ck_diagram_attributes_pk_invariants'),
    sa.CheckConstraint('is_primary_key OR (position >= 1)', name='ck_diagram_attributes_sec_position'),
    sa.ForeignKeyConstraint(['class_id'], ['diagram_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'position', name='uq_diagram_attributes_class_position')
    )
    op.create_index(op.f('ix_diagram_attributes_class_id'), 'diagram_attributes', ['class_id'], unique=False)
    op.drop_constraint(op.f('uq_diagram_classes_project_name'), 'diagram_classes', type_='unique')
    # ### end Alembic commands ###

    # Backfill: Crear una clave primaria 'id' de tipo 'UUID' en position 0 para todas las clases existentes
    import uuid
    from datetime import datetime, timezone

    bind = op.get_bind()
    diagram_classes_table = sa.table(
        'diagram_classes',
        sa.column('id', sa.Uuid()),
    )
    diagram_attributes_table = sa.table(
        'diagram_attributes',
        sa.column('id', sa.Uuid()),
        sa.column('created_date', sa.DateTime(timezone=True)),
        sa.column('modified_date', sa.DateTime(timezone=True)),
        sa.column('deleted_date', sa.DateTime(timezone=True)),
        sa.column('class_id', sa.Uuid()),
        sa.column('name', sa.String(length=255)),
        sa.column('data_type', sa.String(length=50)),
        sa.column('position', sa.Integer()),
        sa.column('is_primary_key', sa.Boolean()),
        sa.column('is_nullable', sa.Boolean()),
    )

    existing_classes = bind.execute(sa.select(diagram_classes_table.c.id)).fetchall()
    now = datetime.now(timezone.utc)
    for row in existing_classes:
        class_id = row[0]
        bind.execute(
            diagram_attributes_table.insert().values(
                id=uuid.uuid4(),
                created_date=now,
                modified_date=now,
                deleted_date=None,
                class_id=class_id,
                name='id',
                data_type='UUID',
                position=0,
                is_primary_key=True,
                is_nullable=False,
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_diagram_classes_project_name'), 'diagram_classes', ['project_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_diagram_attributes_class_id'), table_name='diagram_attributes')
    op.drop_table('diagram_attributes')
    # ### end Alembic commands ###
