"""create agent_activities table

Revision ID: 63101c9ee5c7
Revises: 8e12b45a9901
Create Date: 2026-09-14 16:07:00.741908

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63101c9ee5c7'
down_revision: Union[str, Sequence[str], None] = '8e12b45a9901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_activities_project_id'), 'agent_activities', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_activities_project_id'), table_name='agent_activities')
    op.drop_table('agent_activities')
    # ### end Alembic commands ###
