"""create_diagram_classes_table

Revision ID: 72adc2dd80b2
Revises: 6ed76da51eb7
Create Date: 2026-09-12 13:29:39.581281

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72adc2dd80b2'
down_revision: Union[str, Sequence[str], None] = '6ed76da51eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_classes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_diagram_classes_project_name')
    )
    op.create_index(op.f('ix_diagram_classes_project_id'), 'diagram_classes', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagram_classes_project_id'), table_name='diagram_classes')
    op.drop_table('diagram_classes')
    # ### end Alembic commands ###
