from enum import StrEnum


class DiagramRelationHandle(StrEnum):
    TOP_LEFT = "TOP_LEFT"
    TOP_CENTER = "TOP_CENTER"
    TOP_RIGHT = "TOP_RIGHT"
    RIGHT_TOP = "RIGHT_TOP"
    RIGHT_CENTER = "RIGHT_CENTER"
    RIGHT_BOTTOM = "RIGHT_BOTTOM"
    BOTTOM_RIGHT = "BOTTOM_RIGHT"
    BOTTOM_CENTER = "BOTTOM_CENTER"
    BOTTOM_LEFT = "BOTTOM_LEFT"
    LEFT_BOTTOM = "LEFT_BOTTOM"
    LEFT_CENTER = "LEFT_CENTER"
    LEFT_TOP = "LEFT_TOP"
