from enum import StrEnum


class DiagramRelationType(StrEnum):
    ASSOCIATION = "ASSOCIATION"
    AGGREGATION = "AGGREGATION"
    COMPOSITION = "COMPOSITION"
    GENERALIZATION = "GENERALIZATION"
    REALIZATION = "REALIZATION"
    DEPENDENCY = "DEPENDENCY"
