from enum import StrEnum


class AgentActionType(StrEnum):
    CREATE_CLASS = "CREATE_CLASS"
    DELETE_CLASS = "DELETE_CLASS"
    RENAME_CLASS = "RENAME_CLASS"
    CREATE_ATTRIBUTE = "CREATE_ATTRIBUTE"
    UPDATE_ATTRIBUTE = "UPDATE_ATTRIBUTE"
    DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE"
    CREATE_RELATION = "CREATE_RELATION"
    DELETE_RELATION = "DELETE_RELATION"
    RENAME_RELATION = "RENAME_RELATION"
